global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers: []

rule_files:
  - /etc/prometheus/alerts/alert_rules.yml

scrape_configs:
  - job_name: "sentiment-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["app:8000"]


