
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: sentiment_app
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
      - ../run.py:/app/run.py
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../monitoring/alerts/alert_rules.yml:/etc/prometheus/alerts/alert_rules.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - ../monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards